package com.tagpulse.gateway.core.outbox

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import kotlinx.coroutines.flow.Flow

/**
 * Data-access for the durable outbox (plan §7).
 *
 * All mutating/one-shot reads are `suspend` (Room runs them off the main thread);
 * the `observe*` reads return [Flow] for reactive consumers (e.g. a future
 * status UI). Ordering for the pending queue is **oldest-first** by
 * `created_at`, tie-broken by `id` (stable insertion order).
 *
 * M3 uses only insert + the pending/count/purge/evict reads; the
 * state/attempts mutators exist for the M4 drainer but are **not driven** in M3.
 */
@Dao
interface OutboxDao {

    /** Insert a row; returns the autogenerated [OutboxItem.id]. */
    @Insert
    suspend fun insert(item: OutboxItem): Long

    /** All rows in a given [OutboxState], oldest-first. */
    @Query(
        "SELECT * FROM outbox_items WHERE state = :state " +
            "ORDER BY created_at ASC, id ASC",
    )
    suspend fun byState(state: String): List<OutboxItem>

    /** Reactive view of rows in a given state, oldest-first. */
    @Query(
        "SELECT * FROM outbox_items WHERE state = :state " +
            "ORDER BY created_at ASC, id ASC",
    )
    fun observeByState(state: String): Flow<List<OutboxItem>>

    /** Total row count. */
    @Query("SELECT COUNT(*) FROM outbox_items")
    suspend fun count(): Int

    /** Reactive total row count. */
    @Query("SELECT COUNT(*) FROM outbox_items")
    fun observeCount(): Flow<Int>

    /** Row count in a given state. */
    @Query("SELECT COUNT(*) FROM outbox_items WHERE state = :state")
    suspend fun countByState(state: String): Int

    /**
     * Update a row's [OutboxState] + attempt count (the M4 drainer's transition).
     * Returns the number of rows affected.
     */
    @Query("UPDATE outbox_items SET state = :state, attempts = :attempts WHERE id = :id")
    suspend fun updateStateAndAttempts(id: Long, state: String, attempts: Int): Int

    /** Delete a single row by id. Returns rows affected. */
    @Query("DELETE FROM outbox_items WHERE id = :id")
    suspend fun deleteById(id: Long): Int

    /**
     * Age cap: delete rows whose **capture time** predates [cutoff] (epoch ms).
     * Capture time (not insertion time) is what the backend's 24 h clock rejects,
     * so purging by it avoids a guaranteed dead-letter (plan §4/§7). Returns rows
     * deleted.
     */
    @Query("DELETE FROM outbox_items WHERE captured_at < :cutoff")
    suspend fun deleteCapturedBefore(cutoff: Long): Int

    /**
     * Size cap (atomic): keep only the [maxItems] newest rows (by insertion
     * order), deleting the rest in a **single statement**. Folding the count +
     * eviction into one `DELETE ... WHERE id NOT IN (SELECT ... LIMIT :maxItems)`
     * closes the read-then-delete race a second writer (the M4 drainer) would open
     * (ledger **C-1TQZ**): a separate `count()` then `deleteOldest(count-cap)` could
     * over-evict if a row landed between the two. Returns rows deleted. Evicting
     * *unsent* rows is bounded data-loss protection (see [Outbox]).
     */
    @Query(
        "DELETE FROM outbox_items WHERE id NOT IN (" +
            "SELECT id FROM outbox_items ORDER BY created_at DESC, id DESC LIMIT :maxItems)",
    )
    suspend fun evictToCap(maxItems: Int): Int
}
