package com.tagpulse.gateway.core.outbox

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * A single durable outbox row — one normalized `Observation` awaiting relay.
 *
 * Mirrors the plan §7 row shape
 * `{id, subject, source, captured_at, payload_json, location_json, state,
 * attempts, created_at}`, with the composite `subject`/`source` value objects
 * flattened into primitive columns so Room needs **no** type converters (keeps
 * the footprint lean and the schema transparent).
 *
 * The explicit [subjectKind]/[subjectId] + [sourceModality]/[sourceGatewayDeviceId]
 * columns are the design's **cheap hedge** (plan §3/§7): every queued reading
 * records *what* was observed and *by which modality on which gateway* — never an
 * implicit "self".
 *
 * Timestamps ([capturedAt], [createdAt]) are stored as epoch milliseconds (UTC),
 * which is monotone-orderable for the pending queue + age cap and free of any
 * locale/formatting ambiguity. [payloadJson]/[locationJson] carry the
 * `Observation.payload` / `location` as JSON strings (see [OutboxJson]).
 *
 * @property id autogenerated row id; also the stable insertion order.
 * @property state the [OutboxState] name; **always `PENDING` at M3**.
 * @property attempts relay attempt count; **always 0 at M3** (no sender yet).
 */
@Entity(tableName = "outbox_items")
data class OutboxItem(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long = 0,

    @ColumnInfo(name = "subject_kind")
    val subjectKind: String,

    @ColumnInfo(name = "subject_id")
    val subjectId: String,

    @ColumnInfo(name = "source_modality")
    val sourceModality: String,

    @ColumnInfo(name = "source_gateway_device_id")
    val sourceGatewayDeviceId: String?,

    @ColumnInfo(name = "captured_at")
    val capturedAt: Long,

    @ColumnInfo(name = "payload_json")
    val payloadJson: String,

    @ColumnInfo(name = "location_json")
    val locationJson: String?,

    @ColumnInfo(name = "state")
    val state: String,

    @ColumnInfo(name = "attempts")
    val attempts: Int,

    @ColumnInfo(name = "created_at")
    val createdAt: Long,
)
